// @vitest-environment jsdom
import React from "react";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { RequestProvider, useRequest } from "@/state/RequestContext";
import { SearchResults } from "@/app/(portal)/search/SearchResults";
import type { MeResponse } from "@rufdiamond/contracts";
import type { FigureDetail } from "@/types/catalog";
import { FigureWorkspace } from "@/app/(portal)/figures/[figureId]/FigureWorkspace";
import { MachineProvider } from "@/state/MachineContext";
const navigation = vi.hoisted(() => ({ push: vi.fn(), back: vi.fn() }));
vi.mock("next/navigation", () => ({ useRouter: () => navigation }));
const session: MeResponse = { id: "user", companyId: "company", displayName: "Synthetic", csrfToken: "test", capabilities: ["parts.record.view"], company: { id: "company", name: "Synthetic", type: "customer", defaultShippingAddress: null }, scopes: { brandIds: "all", accountIds: "all", fleet: "all", environment: "published", priceTier: "none", scopeVersion: "1", canViewPrices: false } };
const part = { id: "10000000-0000-4000-8000-000000000001", releasePartId: "rp", partNumber: "P", description: "Authorized part", manufacturer: null, currency: "CAD" as const, status: "active" as const, supersededByPartId: null, requires: [] };
const row = { part, figureId: "figure", groupNo: "A.1", assemblyName: "Assembly", systemName: "System", modelName: "Model", serial: "Range" };
const response = () => Response.json({ items: [row], nextCursor: null, releases: [{ modelId: "model", releaseId: "release", revision: 1 }] });
function Status() { const request = useRequest(); return <span>{request.linesHydrated ? `Committed ${request.lines.length}` : "Hydrating"}</span>; }
const tree = (search = true) => <RequestProvider apiSession={session}><Status />{search ? <SearchResults query="P" mode="part" brand="" rows={[row]} /> : <p>Another page</p>}</RequestProvider>;
afterEach(() => { cleanup(); sessionStorage.clear(); vi.unstubAllGlobals(); navigation.push.mockClear(); });
it("keeps selected search rows pending and on rejection without announcing success or navigating", async () => {
  let complete!: (response: Response) => void;
  vi.stubGlobal("fetch", () => new Promise<Response>(resolve => { complete = resolve; }));
  render(tree());
  await screen.findByText("Committed 0");
  fireEvent.click(screen.getByRole("checkbox", { name: "Select P" }));
  fireEvent.click(screen.getByRole("button", { name: "Request a quote" }));
  expect((screen.getByRole("checkbox", { name: "Select P" }) as HTMLInputElement).checked).toBe(true);
  expect((screen.getByRole("button", { name: "Request a quote" }) as HTMLButtonElement).disabled).toBe(true);
  expect(screen.queryByText(/added to the cart/)).toBeNull();
  expect(navigation.push).not.toHaveBeenCalled();
  await act(async () => complete(new Response(null, { status: 403 })));
  expect(screen.getByRole("alert")).toBeTruthy();
  expect((screen.getByRole("checkbox", { name: "Select P" }) as HTMLInputElement).checked).toBe(true);
  expect(screen.getByText("Committed 0")).toBeTruthy();
  expect(navigation.push).not.toHaveBeenCalled();
});
it("announces success and clears selection only after the addition commits", async () => {
  let complete!: (response: Response) => void;
  vi.stubGlobal("fetch", () => new Promise<Response>(resolve => { complete = resolve; }));
  render(tree()); await screen.findByText("Committed 0");
  fireEvent.click(screen.getByRole("checkbox", { name: "Select P" }));
  fireEvent.click(screen.getByRole("button", { name: /Add to cart/ }));
  expect(screen.queryByText(/added to the cart/)).toBeNull();
  await act(async () => complete(response()));
  await screen.findByText(/added to the cart/);
  expect(screen.getByText("Committed 1")).toBeTruthy();
  expect((screen.getByRole("checkbox", { name: "Select P" }) as HTMLInputElement).checked).toBe(false);
});
it("finishes the global addition without navigating back from an unmounted search caller", async () => {
  let complete!: (response: Response) => void;
  vi.stubGlobal("fetch", () => new Promise<Response>(resolve => { complete = resolve; }));
  const view = render(tree()); await screen.findByText("Committed 0");
  fireEvent.click(screen.getByRole("checkbox", { name: "Select P" }));
  fireEvent.click(screen.getByRole("button", { name: "Request a quote" }));
  view.rerender(tree(false));
  await act(async () => complete(response()));
  await waitFor(() => expect(screen.getByText("Committed 1")).toBeTruthy());
  expect(screen.getByText("Another page")).toBeTruthy();
  expect(navigation.push).not.toHaveBeenCalled();
});
it("opens the quote only after the search addition is committed", async () => {
  let complete!: (response: Response) => void;
  vi.stubGlobal("fetch", () => new Promise<Response>(resolve => { complete = resolve; }));
  render(tree()); await screen.findByText("Committed 0");
  navigation.push.mockImplementationOnce(() => expect(screen.getByText("Committed 1")).toBeTruthy());
  fireEvent.click(screen.getByRole("checkbox", { name: "Select P" }));
  fireEvent.click(screen.getByRole("button", { name: "Request a quote" }));
  expect(navigation.push).not.toHaveBeenCalled();
  await act(async () => complete(response()));
  expect(navigation.push).toHaveBeenCalledWith("/request");
});
it("does not navigate for an old query when Next retains the search component", async () => {
  let complete!: (response: Response) => void;
  vi.stubGlobal("fetch", () => new Promise<Response>(resolve => { complete = resolve; }));
  const view = render(tree()); await screen.findByText("Committed 0");
  fireEvent.click(screen.getByRole("checkbox", { name: "Select P" }));
  fireEvent.click(screen.getByRole("button", { name: "Request a quote" }));
  view.rerender(<RequestProvider apiSession={session}><Status /><SearchResults query="Another query" mode="part" brand="" rows={[]} /></RequestProvider>);
  await act(async () => complete(response()));
  expect(screen.getByText("Committed 1")).toBeTruthy();
  expect(navigation.push).not.toHaveBeenCalled();
  expect(screen.queryByText(/added to the cart/)).toBeNull();
});
it("permits A to B to A query round trips without an old completion settling the new addition", async () => {
  const completions: ((response: Response) => void)[] = [];
  vi.stubGlobal("fetch", () => new Promise<Response>(resolve => { completions.push(resolve); }));
  const search = (query: string) => <RequestProvider apiSession={session}><Status /><SearchResults query={query} mode="part" brand="" rows={[row]} /></RequestProvider>;
  const view = render(search("A")); await screen.findByText("Committed 0");
  fireEvent.click(screen.getByRole("checkbox", { name: "Select P" }));
  fireEvent.click(screen.getByRole("button", { name: "Request a quote" }));
  view.rerender(search("B"));
  view.rerender(search("A"));
  expect((screen.getByRole("button", { name: "Request a quote" }) as HTMLButtonElement).disabled).toBe(false);
  fireEvent.click(screen.getByRole("button", { name: "Request a quote" }));
  await act(async () => completions[0](response()));
  expect((screen.getByRole("button", { name: "Request a quote" }) as HTMLButtonElement).disabled).toBe(true);
  expect(navigation.push).not.toHaveBeenCalled();
  expect(screen.queryByText(/added to the cart/)).toBeNull();
  await act(async () => completions[1](response()));
  expect((screen.getByRole("button", { name: "Request a quote" }) as HTMLButtonElement).disabled).toBe(false);
  expect(navigation.push).toHaveBeenCalledOnce();
  expect(screen.getByText(/added to the cart/)).toBeTruthy();
});
it("keeps a figure on its selected parts until quote additions succeed, and exposes rejection", async () => {
  const detail: FigureDetail = { release: { modelId: "model", releaseId: "release", revision: 1 }, mapping: null, figure: { id: "figure", variantId: "variant", systemId: "system", name: "Assembly", groupNo: "A.1", drawingFileId: null, status: "published" }, system: { id: "system", name: "System", sortOrder: 1 }, variant: { id: "variant", modelId: "model", label: "Range", serialFrom: null, serialTo: null, catalogRevision: null }, drawing: null, rows: [{ part, figurePart: { id: "row", figureId: "figure", partId: part.id, qty: 1, remarks: null, serviceable: true }, calloutNumbers: ["A*"] }], callouts: [] };
  let complete!: (response: Response) => void;
  vi.stubGlobal("fetch", () => new Promise<Response>(resolve => { complete = resolve; }));
  render(<MachineProvider persist={false}><RequestProvider apiSession={session}><Status /><FigureWorkspace detail={detail} usage={{}} sheet="1" index={0} total={1} previousId={null} nextId={null} firstId={null} lastId={null} /></RequestProvider></MachineProvider>);
  await screen.findByText("Committed 0");
  fireEvent.click(screen.getByRole("checkbox", { name: "Add P to the cart" }));
  fireEvent.click(screen.getByRole("button", { name: "Request a quote" }));
  expect(screen.getByRole("button", { name: "Request a quote" }).getAttribute("aria-pressed")).toBe("false");
  await act(async () => complete(new Response(null, { status: 409 })));
  expect(screen.getByRole("alert")).toBeTruthy();
  expect((screen.getByRole("checkbox", { name: "Add P to the cart" }) as HTMLInputElement).checked).toBe(true);
  fireEvent.click(screen.getByRole("button", { name: "Request a quote" }));
  await act(async () => complete(response()));
  await waitFor(() => expect(screen.getByRole("button", { name: "Request a quote" }).getAttribute("aria-pressed")).toBe("true"));
  expect(screen.getByText("Committed 1")).toBeTruthy();
});
